import { CustomizationPage, EPageType } from '../pages/СustomizationPage/СustomizationPage'
import { Navigate } from 'react-router-dom'
import { NotExistPage } from '../pages/NotExistPage/NotExistPage.tsx'
import { CabinetPage } from '../pages/CabinetPage/CabinetPage.tsx'
import { TRoute } from '../../shared-react-components/AlexRouter/AlexRouter.tsx'
import { customizationPageConfig } from '../config/customizationPageConfig.tsx'

export const routesList: TRoute[] = [
    {
        path: '/',
        name: 'Главная',
        component: null,
    },

    {
        path: '*',
        name: 'Не существует',
        component: <NotExistPage/>,
    },

    {
        path: 'cabinet',
        name: 'Личный кабинет',
        component: <CabinetPage/>,
    },

    {
        path: `customization/events`,
        name: 'События',
        component: <Navigate to={`/customization/events/${EPageType.table}`}/>,
    },
    {
        path: `customization/events/${EPageType.table}`,
        name: 'Таблица событий',
        component: <CustomizationPage config={customizationPageConfig}/>,
    },
    {
        path: `customization/events/${EPageType.view}`,
        name: 'Событие',
        component: <CustomizationPage config={customizationPageConfig}/>,
    },
    {
        path: `customization/events/${EPageType.edit}`,
        name: 'Настройка события',
        component: <CustomizationPage config={customizationPageConfig}/>,
    },
    {
        path: `customization/events/${EPageType.add}`,
        name: 'Добавление события',
        component: <CustomizationPage config={customizationPageConfig}/>,
    },
]

const mapRoutesListPaths = (routesList: TRoute[]): string[] => {
    const resultArr: string[] = []

    routesList.map((item) => {
        resultArr.push(item.path)
        if (item.routes) {
            resultArr.push(...mapRoutesListPaths(item.routes))
        }
    })

    return resultArr
}

const mapRoutesListNames = (routesList: TRoute[]): [string, string][] => {
    const resultArr: [string, string][] = []

    routesList.map((item) => {
        resultArr.push([item.path, item.name])
        if (item.routes) {
            resultArr.push(...mapRoutesListNames(item.routes))
        }
    })

    return resultArr
}
export const autoGeneratedRoutesListMap = new Map(mapRoutesListNames(routesList))
export const autoGeneratedAllowedLinks = mapRoutesListPaths(routesList)